project:
  type: website

website:
  title: "Sophie X. Chen"
  favicon: "favicon.png"
  navbar:
    left:
      - href: index.qmd
        text: Blog
      - about.qmd
      - html: |
        <a href="https://github.com/sophiexchen" target="_blank">
          <img src="https://github.githubassets.com/images/modules/logos_page/GitHub-Mark.png" alt="GitHub" style="width: 30px; height: auto;">
        </a>
format:
  html:
    css: styles.css
    theme: default
