project:
  type: website

website:
  title: "Sophie X. Chen"
  navbar:
    left:
      - href: index.qmd
        text: Blog
      - about.qmd

format:
  html:
    favicon: animal.png
    css: styles.css
    theme: default  
    
    



