project:
  type: website

website:
  title: "Sophie X. Chen"
  favicon: "favicon.png"
  navbar:
    left:
      - href: index.qmd
        text: Blog
      - about.qmd
      - href: https://github.com/sophiexchen
        text: GitHub
        target: "_blank"

format:
  html:
    css: styles.css
    theme: default
