project:
  type: website

website:
  title: "Sophie X. Chen"
  favicon: "favicon.png"
  navbar:
    right:
      - href: index.qmd
        text: Blog
      - about.qmd
      - text: Resume
        href: files/sophies-resume.pdf
        target: "_blank"
      - icon: "github"
        href: "https://github.com/sophiexchen"
        target: _blank
      - icon: linkedin
        href: "https://www.linkedin.com/in/sophiexchen/"
        target: _blank
      - icon: "envelope"
        href: "mailto:philosophiexc@gmail.com"
        target: _blank

  listing:
    contents: posts
    sort: "date desc"
    type: default
    categories: true
    sort-ui: false
    filter-ui: false
    feed: true

format:
  html:
    css: styles.css
    theme: default
